### PR TITLE
Initial layout f341-market

### PR DESCRIPTION
**Pull request by taylordowns2000**

### CODE REVIEW

**Comment by taylordowns2000** [comment]
@suninthesky  , you're actually all set to use this branch on our Repo. I'm pulling your changes in here so that I don't need to clone another repo locally to test. Excited to see what it looks like!

**Comment by taylordowns2000** [comment]
@suninthesky , this is classy stuff. Love it. Way cleaner than it was before!

**Comment by suninthesky** [comment]
Thanks @taylordowns2000. I hadn't accepted your invite, now all set. It's funny, but I'm being far more disciplined then when I'm hacking away on Beehive! Hope to make some more progress over the weekend.

**Comment by taylordowns2000** [comment]
Love it!

**Pull request merged**
